name: Setup Gradle Environment

inputs:
  java-version:
    description: Java version
    required: false
    default: '21'
  java-distributor:
    description: Java distributor
    required: false
    default: 'temurin'
  working-directory:
    description: Directory of project on github
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Print App Parameters
      uses: JustSiHeshteger/pipeline-action/echo-app-parameters@c22e8e09b00e1f00f03255f5ada92ac45be31cf9
      with:
        java-version: ${{ inputs.java-version }}
        java-distributor: ${{ inputs.java-distributor }}
        working-directory: ${{ inputs.working-directory }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distributor }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle wrapper executable
      shell: bash
      run: chmod +x ${{ inputs.working-directory }}/gradlew