name: Setup Gradle Environment

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTIBUTOR }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle wrapper executable
      shell: bash
      run: chmod +x ${{ env.WORKING_DIRECTORY }}/gradlew