name: Setup Gradle Environment

inputs:
  java-version:
    description: Java version
    required: true
  java-distributor:
    description: Java distributor
    required: true
  working-directory:
    description: Directory of project on github
    required: true

runs:
  using: composite
  steps:
    - name: Output java env
      shell: bash
      run: echo "Java version ${{ inputs.java-version }}; \
        Java Distibutor ${{ inputs.java-distributor }}; \
        Working directory ${{ inputs.working-directory }}"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distributor }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle wrapper executable
      shell: bash
      run: chmod +x ${{ inputs.working-directory }}/gradlew