name: 'Setup Gradle Environment'

inputs:
  java_version:
    description: "Java version"
    required: false
    default: '21'
  java_distributor:
    description: "Java distributor"
    required: false
    default: 'temurin'

runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distributor }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle wrapper executable
      shell: bash
      run: chmod +x ./gradlew