name: Integration Test App

runs:
  using: composite
  steps:
    - name: Setup Gradle Environment
      uses: JustSiHeshteger/pipeline-action/setup-gradle-env@v2

    - name: Run Tests
      shell: bash
      run: ${{ env.WORKING_DIRECTORY }}/gradlew integrationTest