name: SonarCloud Analyze

inputs:
  working_directory:
    description: "Directory of project on github"
    required: false
    default: .

runs:
  using: composite
  steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#      with:
#        fetch-depth: 0

    - name: Setup Gradle Environment
      uses: ./setup-gradle-env

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Run Sonar
      working-directory: ${{ inputs.working-directory }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: bash
      run: ./gradlew sonar
