name: SonarCloud Analyze

runs:
  using: composite
  steps:
    - name: Setup Gradle Environment
      uses: JustSiHeshteger/pipeline-action/setup-gradle-env@v2

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Run Sonar
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      shell: bash
      run: ${{ env.WORKING_DIRECTORY }}/gradlew sonar
