name: Docker Build

inputs:
  working-directory:
    description: Directory of project on github
    required: false
    default: .
  artifact-name:
    description: Name of build artifact
    required: false
    default: app-build
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: Docker image tag
    required: true
  base-image:
    description: Docker Java Image
    required: false
    default: eclipse-temurin:21-jre-alpine

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy Dockerfile from action repo
      shell: bash
      run: |
        cp "${{ github.action_path }}/Dockerfile" ./Dockerfile

    - name: Print Dockerfile
      shell: bash
      run: | 
        echo "Action path: ${{ github.action_path }}" 
        ls -la "${{ github.action_path }}"

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Find downloaded JAR
      shell: bash
      run: |
        JAR_PATH=$(ls ${{ inputs.working-directory }}/*.jar | head -n 1)
        echo "Found JAR: $JAR_PATH"
        echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

    - name: Copy JAR to Docker build context
      shell: bash
      run: |
        cp "${{ env.JAR_PATH }}" app.jar
        echo "JAR_FILE=app.jar" >> $GITHUB_ENV


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: false
        tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
        build-args: |
          JAR_FILE=${{ env.JAR_PATH }}
          BASE_IMAGE=${{ inputs.base-image }}