name: Docker Build

inputs:
  java-version:
    description: Java version
    required: false
    default: '21'
  java-distributor:
    description: Java distributor
    required: false
    default: temurin
  working-directory:
    description: Directory of project on github
    required: false
    default: .
  artifact-name:
    description: Name of build artifact
    required: false
    default: app-build
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: Docker image tag
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: "${{ inputs.working-directory }}/*.jar"

    - name: Docker Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        docker build \
        -f ${{ github.action_path }}/Dockerfile \
        --build-arg JAR_FILE=artifact/app.jar \
        --build-arg JAVA_VERSION=${{ inputs.java-version }} \
        --build-arg JAVA_DISTRIBUTION=${{ inputs.java-distributor }} \
        -t ${{ inputs.image-name }}:${{ inputs.image-tag }} \
        .