name: Publish Build Artifact

inputs:
  artifact-name:
    description: Artifact name
    required: false
    default: 'artifact'
  working-directory:
    description: Project directory
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Show downloaded files
      shell: bash
      run: |
        echo "Workspace:"
        pwd
        echo "Tree:"
        find . -type f

    - name: List build/libs
      shell: bash
      run: ls -la ${{ inputs.working-directory }}/build/libs

    - name: Prepare artifact directory
      shell: bash
      run: |
        set -e
        mkdir -p artifact

        echo "Searching JAR in ${{ inputs.working-directory }}/build/libs"
        JAR_FILE=$(ls ${{ inputs.working-directory }}/build/libs/*.jar | head -n 1)

        if [ -z "$JAR_FILE" ]; then
          echo "JAR file not found"
          exit 1
        fi

        echo "Found JAR: $JAR_FILE"
        cp "$JAR_FILE" artifact/app.jar

    - name: Resolve version from Gradle
      shell: bash
      run: |
        set -e
        VERSION=$(
          ${{ inputs.working-directory }}/gradlew -q properties \
          | grep '^version:' \
          | awk '{print $2}'
        )

        if [ -z "$VERSION" ]; then
          echo "Version not resolved"
          exit 1
        fi

        echo "Resolved version: $VERSION"
        echo "$VERSION" > artifact/version.txt