name: Publish Build Artifact

inputs:
  artifact-name:
    description: Artifact name
    required: false
    default: 'artifact'
  working-directory:
    description: Project directory
    required: false
    default: '.'
  application-name:
    description: Application Name
    required: false
    default: 'application-jar'

runs:
  using: composite
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: List workspace
      shell: bash
      run: ls -la ${{ inputs.working-directory }}

    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.application-name }}
        path: "${{ inputs.working-directory }}/*.jar"

    - name: Print Artifact URL
      shell: bash
      run: | 
        echo "Artifact URL: ${{ steps.upload.outputs.artifact-url }}"